### ISSUE TITLE
Add some references to the Plutus Pioneer Program

### ISSUE THREAD

**Issue by nielstron** [OpShin/opshin-pioneer-program#26]
Appearently it is not entirely clear to new users how to follow along this repository best (see https://twitter.com/Redd_Spark/status/1641738327224197120?t=_7PgivOdp9eDqS0pTs0WeA&s=19)

Maybe we can either copy the descriptions from the [plutus pioneer program ](https://github.com/input-output-hk/plutus-pioneer-program/blob/fourth-iteration/readme.md) or add a number of links / references at the right places?

**Comment by juliusfrost** [comment]
I documented some instructions on how to follow along with the pioneer lectures. Please let me know if if there's other ways to give a high level structural overview.

In general, I think the hardest part for beginners is setting up the environment, especially if they don't have any python or docker background. More specific questions are probably best directed towards being asked in discord.

**Comment by nielstron** [comment]
Thats already great. Lets add some pointers to the discord server in the description just as you mentioned 

> More specific questions are probably best directed towards being asked in discord.

Also a discord badge https://github.com/ashmonty/discord-md-badge

**Comment by juliusfrost** [comment]
Awesome. I just added the discord link in cb4f98dbce13a5bf4a61d96ddfc17969580cdc94
