### ISSUE TITLE
Add kupo per default to the chain context

### ISSUE THREAD

**Issue by nielstron** [OpShin/opshin-pioneer-program#37]
Kupo is blazing fast for querying UTxOs and kupo + ogmios testnet instances are below the free threshold on demeter.run. I therefore suggest to add a kupo instance per default (default might be None, but set if the OS parameters are set).

**Comment by juliusfrost** [comment]
After #43 is merged, I'll look into making the chain context customizable (including `MockChainContext` and `BlockFrostChainContext`). I'm thinking of implementing `get_context() -> ChainContext` in the `scripts` dir, and then make integration tests for those using subprocesses.
