### ISSUE TITLE
Week05 -> Burn Tokens

### ISSUE THREAD

**Issue by Ursify** [OpShin/opshin-pioneer-program#50]
Hi Guys,

Could you please take a look to mint.py? I was trying to burn tokens after minting them, but is not working with negative values.
First, I notice that minting script is creating a UTxO with 2000000 lovelace + Native Assets, and I when running mint.py it will not pick the right UTxO since is looking for those with at least 3000000 lovelace. 

Forcing my original UTxOs created with mint.py gave me an error that they don't have enough funds.( Inputs / Outputs doesn't match)

Then, I tried adding more than one input to have enough funds for this transaction, also I created another Native Asset with enough funds to be able to load it to the script, both gave me an error in Ogmios.

Input UTxO with enough funds gave me this error:
![image](https://user-images.githubusercontent.com/35331253/235347274-54e1c40c-ce92-44ab-aad0-14db6051aad2.png)

Let me know in case that you need more information from my side.
Cheers,

**Comment by nielstron** [comment]
https://github.com/OpShin/opshin-pioneer-program/blob/5800218a35dd3ecd3ce90d4cbee329206bd8df2e/src/week05/scripts/mint.py#L84

In this line, the mint value must be ommitted from the output in case the mint amount is negative.
